{{- if .Values.gateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.gateway.name }}
spec:
  selector:
    app: {{ .Values.gateway.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.gateway.port }}
    name: http
  type: ClusterIP

{{- if .Values.gateway.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.gateway.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.gateway.name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.gateway.route.tls.termination }}
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
{{- end }}
