apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hacohen-flywheel

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: nemo-gateway
  component: api-gateway
