apiVersion: v2
name: flywheel-prerequisites
description: Infrastructure prerequisites for NVIDIA Data Flywheel on OpenShift
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: redis
    version: 24.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mongodb
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
